### ISSUE TITLE
Missing build dependencies on Debian

### ISSUE THREAD

**Issue by WilliamRutherford** [Eloston/ungoogled-chromium#102]
`2016-10-11 14:30:35,332 - INFO: Applying patches via quilt...
Traceback (most recent call last):
  File "build.py", line 57, in <module>
    exit(main())
  File "build.py", line 39, in main
    builder.apply_patches()
  File "/home/william/bin/ungoogled-chromium/buildlib/linux.py", line 63, in apply_patches
    cwd=str(self._sandbox_dir))
  File "/home/william/bin/ungoogled-chromium/buildlib/common.py", line 91, in _run_subprocess
    return _util.subprocess_run(*args, env=new_env, **kwargs)
  File "/home/william/bin/ungoogled-chromium/buildlib/_util.py", line 232, in subprocess_run
    with subprocess.Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)`

`FileNotFoundError: [Errno 2] No such file or directory: 'quilt'
`  
  
Here is the output when build.py runs. It says it cannot find the directory quilt. I'm trying to build on Debian Jessie.

**Comment by tonowoe** [comment]
I had the same error. You need the dev-packages to get packaging work in Debian.

Just run this:

`sudo apt-get install packaging-dev `

**Comment by Eloston** [comment]
Huh, I didn't know this package existed. Though I'm pretty certain you just need to manually install `quilt` and `build-essential` in order to build Chromium. I'll amend the build instructions.
