### ISSUE TITLE
AUR package build issue

### ISSUE THREAD

**Issue by smoorg** [Eloston/ungoogled-chromium#1024]
**Describe the bug**
I am not able to build package from `aur` repositories on Arch Linux.

**To Reproduce**
1. Clone `git clone https://aur.archlinux.org/ungoogled-chromium.git`
2. Go to respective folder
3. Build `makepkg -sri`

**Expected behavior**
The AUR package should build correctly from git repository.

**Environment (please complete the following information):**
 - OS/Platform and version: archlinux (5.6.6-arch1-1)
 - ungoogled-chromium version: 81.0.4044.129-1 

**Additional context**
```
[smoorg@archlinux ungoogled-chromium]$ makepkg -sri
==> Tworzenie pakietu: ungoogled-chromium 81.0.4044.129-1 (pią, 1 maj 2020, 14:58:45)
==> Sprawdzanie zależności potrzebnych do uruchomienia...
==> Sprawdzanie zależności potrzebnych do budowy...
==> Pobieranie źródeł...
  -> Znaleziono chromium-81.0.4044.129.tar.xz
  -> Znaleziono chromium-launcher-6.tar.gz
  -> Znaleziono 81.0.4044.129-1.tar.gz
  -> Znaleziono 54bc225e3a263be9a6b7dc5a33c5d713d9c42716.tar.gz
==> Sprawdzanie plików source za pomocą sha256sums...
    chromium-81.0.4044.129.tar.xz ... Zgadza się
    chromium-launcher-6.tar.gz ... Zgadza się
    81.0.4044.129-1.tar.gz ... Zgadza się
    54bc225e3a263be9a6b7dc5a33c5d713d9c42716.tar.gz ... Zgadza się
==> Rozpakowywanie źródeł...
  -> Rozpakowywanie chromium-81.0.4044.129.tar.xz za pomocą bsdtar
  -> Rozpakowywanie chromium-launcher-6.tar.gz za pomocą bsdtar
  -> Rozpakowywanie 81.0.4044.129-1.tar.gz za pomocą bsdtar
  -> Rozpakowywanie 54bc225e3a263be9a6b7dc5a33c5d713d9c42716.tar.gz za pomocą bsdtar
==> Rozpoczynanie prepare()...
  -> Pruning binaries
  -> Applying patches
INFO: Applying patches from /home/matr/aur/ungoogled-chromium/src/ungoogled-chromium-81.0.4044.129-1/patches
INFO: * Applying 0001-fix-building-without-safebrowsing.patch (1/83)
patching file chrome/browser/BUILD.gn
patching file chrome/browser/browser_process.h
patching file chrome/browser/browser_process_impl.cc
patching file chrome/browser/browser_process_impl.h
patching file chrome/browser/browsing_data/chrome_browsing_data_remover_delegate.cc
patching file chrome/browser/chrome_content_browser_client.cc
patching file chrome/browser/component_updater/file_type_policies_component_installer.cc
patching file chrome/browser/download/chrome_download_manager_delegate.cc
patching file chrome/browser/download/download_item_model.cc
patching file chrome/browser/download/download_prefs.cc
patching file chrome/browser/download/download_target_determiner.cc
patching file chrome/browser/extensions/api/downloads/downloads_api.cc
patching file chrome/browser/extensions/api/downloads/downloads_api.h
patching file chrome/browser/extensions/api/safe_browsing_private/safe_browsing_private_api.cc
patching file chrome/browser/extensions/api/webstore_private/webstore_private_api.cc
patching file chrome/browser/extensions/blacklist_state_fetcher.cc
patching file chrome/browser/extensions/blacklist_state_fetcher.h
patching file chrome/browser/metrics/chrome_metrics_service_client.cc
patching file chrome/browser/net/trial_comparison_cert_verifier_controller.cc
patching file chrome/browser/profiles/chrome_browser_main_extra_parts_profiles.cc
patching file chrome/browser/profiles/profile_impl.cc
patching file chrome/browser/profiles/profiles_state.cc
patching file chrome/browser/safe_browsing/BUILD.gn
patching file chrome/browser/ssl/security_state_tab_helper.cc
patching file chrome/browser/subresource_filter/chrome_subresource_filter_client.cc
patching file chrome/browser/ui/BUILD.gn
patching file chrome/browser/ui/tab_helpers.cc
patching file chrome/browser/ui/webui/downloads/downloads_dom_handler.cc
patching file chrome/browser/ui/webui/downloads/downloads_dom_handler.h
patching file chrome/browser/ui/webui/interstitials/interstitial_ui.cc
patching file chrome/renderer/chrome_content_renderer_client.cc
patching file components/security_interstitials/content/cert_report_helper.cc
INFO: * Applying 0003-disable-autofill-download-manager.patch (2/83)
patching file components/autofill/core/browser/autofill_download_manager.cc
INFO: * Applying 0005-disable-default-extensions.patch (3/83)
patching file chrome/browser/extensions/component_extensions_whitelist/whitelist.cc
patching file chrome/browser/extensions/component_loader.cc
patching file chrome/browser/extensions/external_component_loader.cc
patching file chrome/browser/extensions/webstore_installer.cc
INFO: * Applying 0007-disable-web-resource-service.patch (4/83)
patching file components/web_resource/web_resource_service.cc
INFO: * Applying 0009-disable-google-ipv6-probes.patch (5/83)
patching file net/dns/host_resolver_manager.cc
INFO: * Applying 0014-disable-translation-lang-fetch.patch (6/83)
patching file chrome/browser/spellchecker/spellcheck_hunspell_dictionary.cc
patching file components/translate/core/browser/translate_language_list.cc
patching file components/translate/core/browser/translate_ranker_impl.cc
INFO: * Applying 0015-disable-update-pings.patch (7/83)
patching file chrome/updater/configurator.cc
INFO: * Applying 0017-disable-new-avatar-menu.patch (8/83)
patching file components/signin/internal/identity_manager/primary_account_policy_manager_impl.cc
INFO: * Applying 0021-disable-rlz.patch (9/83)
patching file rlz/buildflags/buildflags.gni
INFO: * Applying unrar.patch (10/83)
patching file chrome/browser/safe_browsing/download_protection/file_analyzer.cc
patching file chrome/common/safe_browsing/BUILD.gn
patching file chrome/services/file_util/safe_archive_analyzer.cc
INFO: * Applying safe_browsing-disable-incident-reporting.patch (11/83)
patching file chrome/browser/safe_browsing/incident_reporting/incident_report_uploader_impl.cc
patching file chrome/browser/safe_browsing/incident_reporting/incident_reporting_service.cc
patching file chrome/browser/safe_browsing/safe_browsing_blocking_page.cc
patching file chrome/browser/safe_browsing/safe_browsing_service.cc
patching file components/security_interstitials/core/safe_browsing_loud_error_ui.cc
INFO: * Applying safe_browsing-disable-reporting-of-safebrowsing-over.patch (12/83)
patching file chrome/browser/safe_browsing/client_side_detection_service.cc
INFO: * Applying all-add-trk-prefixes-to-possibly-evil-connections.patch (13/83)
patching file build/mac/tweak_info_plist.py
patching file chrome/browser/chromeos/customization/customization_document.cc
patching file chrome/browser/chromeos/extensions/file_manager/private_api_drive.cc
patching file chrome/browser/chromeos/extensions/file_manager/private_api_misc.cc
patching file chrome/browser/chromeos/file_manager/file_manager_string_util.cc
patching file chrome/browser/extensions/api/cryptotoken_private/cryptotoken_private_api.cc
patching file chrome/browser/extensions/install_signer.cc
patching file chrome/browser/nacl_host/nacl_infobar_delegate.cc
patching file chrome/browser/profiles/profile_avatar_downloader.cc
patching file chrome/browser/resources/chromeos/accessibility/chromevox/background/prefs.js
patching file chrome/browser/resources/default_apps/external_extensions.json
patching file chrome/browser/safe_browsing/client_side_detection_service.cc
patching file chrome/browser/safe_browsing/download_protection/download_feedback.cc
patching file chrome/browser/spellchecker/spellcheck_hunspell_dictionary.cc
patching file chrome/browser/supervised_user/supervised_user_service.cc
patching file chrome/browser/tracing/crash_service_uploader.cc
patching file chrome/browser/ui/views/outdated_upgrade_bubble_view.cc
patching file chrome/browser/ui/webui/ntp/ntp_resource_cache.cc
patching file chrome/common/extensions/chrome_extensions_client.cc
patching file chrome/common/url_constants.cc
patching file chrome/installer/setup/google_chrome_behaviors.cc
patching file chromecast/browser/service/cast_service_simple.cc
patching file chromeos/geolocation/simple_geolocation_provider.cc
patching file cloud_print/virtual_driver/win/port_monitor/port_monitor.cc
patching file components/cloud_devices/common/cloud_devices_urls.cc
patching file components/crash/content/app/breakpad_linux.cc
patching file components/drive/service/drive_api_service.cc
patching file components/feedback/feedback_uploader.cc
patching file components/gcm_driver/gcm_account_tracker.cc
patching file components/history/core/browser/web_history_service.cc
patching file components/invalidation/impl/gcm_network_channel.cc
patching file components/metrics/url_constants.cc
patching file components/password_manager/core/browser/password_store.cc
patching file components/policy/core/common/policy_loader_win.cc
patching file components/policy/resources/policy_templates.json
patching file components/rappor/rappor_service_impl.cc
patching file components/safe_search_api/safe_search/safe_search_url_checker_client.cc
patching file components/search_engines/prepopulated_engines.json
patching file components/translate/core/browser/translate_url_fetcher.cc
patching file components/translate/core/common/translate_util.cc
patching file components/variations/variations_url_constants.cc
patching file content/browser/speech/speech_recognition_engine.cc
patching file content/shell/browser/shell_browser_main_parts.cc
patching file extensions/browser/updater/safe_manifest_parser.cc
patching file extensions/common/extension_urls.cc
patching file google_apis/gaia/gaia_constants.cc
patching file google_apis/gcm/engine/gservices_settings.cc
patching file jingle/notifier/base/gaia_token_pre_xmpp_auth.cc
patching file remoting/base/breakpad_mac.mm
patching file remoting/protocol/jingle_messages.cc
patching file ui/views/examples/webview_example.cc
INFO: * Applying disable-crash-reporter.patch (14/83)
patching file chrome/browser/tracing/crash_service_uploader.cc
patching file third_party/breakpad/breakpad/src/client/linux/sender/google_crash_report_sender.cc
INFO: * Applying disable-google-host-detection.patch (15/83)
patching file chrome/common/google_url_loader_throttle.cc
patching file components/google/core/common/google_util.cc
patching file components/page_load_metrics/browser/page_load_metrics_util.cc
patching file components/page_load_metrics/common/page_load_metrics_util.cc
patching file components/search_engines/template_url.cc
patching file components/variations/net/variations_http_headers.cc
patching file net/base/url_util.cc
INFO: * Applying replace-google-search-engine-with-nosearch.patch (16/83)
patching file components/search_engines/prepopulated_engines.json
INFO: * Applying disable-signin.patch (17/83)
patching file chrome/browser/ui/chrome_pages.cc
INFO: * Applying disable-translate.patch (18/83)
patching file components/translate/content/renderer/translate_agent.cc
patching file components/translate/core/browser/translate_manager.cc
patching file components/translate/core/browser/translate_script.cc
INFO: * Applying disable-untraceable-urls.patch (19/83)
patching file chrome/browser/plugins/plugins_resource_service.cc
patching file chrome/browser/safe_browsing/client_side_model_loader.cc
patching file chrome/browser/safe_browsing/client_side_model_loader.h
patching file rlz/lib/financial_ping.cc
patching file rlz/lib/lib_values.cc
patching file rlz/lib/lib_values.h
INFO: * Applying disable-profile-avatar-downloading.patch (20/83)
patching file chrome/browser/profiles/profile_avatar_downloader.cc
INFO: * Applying disable-gcm.patch (21/83)
patching file components/gcm_driver/gcm_client_impl.cc
INFO: * Applying disable-domain-reliability.patch (22/83)
patching file components/domain_reliability/BUILD.gn
patching file components/domain_reliability/bake_in_configs.py
patching file components/domain_reliability/google_configs.cc
patching file components/domain_reliability/uploader.cc
INFO: * Applying block-trk-and-subdomains.patch (23/83)
patching file chrome/browser/autocomplete/chrome_autocomplete_scheme_classifier.cc
patching file chrome/browser/history/history_utils.cc
patching file chrome/browser/ui/singleton_tabs.cc
patching file components/omnibox/browser/autocomplete_input.cc
patching file components/url_formatter/url_fixer.cc
patching file content/browser/child_process_security_policy_impl.cc
patching file net/BUILD.gn
The next patch would create the file net/url_request/trk_protocol_handler.cc,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file net/url_request/trk_protocol_handler.h,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
patching file net/url_request/url_request.cc
patching file net/url_request/url_request_context_builder.cc
patching file url/url_constants.cc
patching file url/url_constants.h
patching file url/url_util.cc
Traceback (most recent call last):
  File "/home/matr/aur/ungoogled-chromium/src/ungoogled-chromium-81.0.4044.129-1/utils/patches.py", line 250, in <module>
    main()
  File "/home/matr/aur/ungoogled-chromium/src/ungoogled-chromium-81.0.4044.129-1/utils/patches.py", line 246, in main
    args.callback(args, parser.error)
  File "/home/matr/aur/ungoogled-chromium/src/ungoogled-chromium-81.0.4044.129-1/utils/patches.py", line 198, in _apply_callback
    apply_patches(
  File "/home/matr/aur/ungoogled-chromium/src/ungoogled-chromium-81.0.4044.129-1/utils/patches.py", line 132, in apply_patches
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/patch', '-p1', '--ignore-whitespace', '-i', '/home/matr/aur/ungoogled-chromium/src/ungoogled-chromium-81.0.4044.129-1/patches/core/ungoogled-chromium/block-trk-and-subdomains.patch', '-d', '.', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.
==> BŁĄD: Wystąpił błąd w prepare().
    Przerywam...
```

**Comment by braewoods** [comment]
Is the AUR packaging even under our umbrella? If not I can't see why this is here.

**Comment by wchen342** [comment]
That one is based on the archlinux repository. But I am not sure why this error happened, as I didn't see it myself and others didn't report it too. @smoorg Maybe you forgot to delete the `src` folder before run `makepkg` or your AUR wrapper?

**Comment by Eloston** [comment]
Closing because this issue is stale.
