### ISSUE TITLE
Issue When Building Multiple Times on Windows

### ISSUE THREAD

**Issue by Jonatino** [Eloston/ungoogled-chromium#1069]
- OS/Platform and version: Windows 10 x64
 - ungoogled-chromium version: 83

I've been trying all day to get building working on Windows. Sometimes the build fails on this step:

`py build.py`

Which is fine. I fixed the problem and try to run the build again but it then fails with this error.
```
C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows>py build.py
INFO: Downloading required files...
INFO: Downloading "chromium" to "chromium-83.0.4103.97.tar.xz" ...
INFO: C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows\build\downloads_cache\chromium-83.0.4103.97.tar.xz already exists. Skipping download.
INFO: Downloading hashes for "chromium"
INFO: C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows\build\downloads_cache\chromium-83.0.4103.97.tar.xz.hashes already exists. Skipping download.
INFO: Downloading "bison-bin" to "bison-2.4.1-bin.zip" ...
INFO: C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows\build\downloads_cache\bison-2.4.1-bin.zip already exists. Skipping download.
INFO: Downloading "bison-dep" to "bison-2.4.1-dep.zip" ...
INFO: C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows\build\downloads_cache\bison-2.4.1-dep.zip already exists. Skipping download.
INFO: Downloading "bison-lib" to "bison-2.4.1-lib.zip" ...
INFO: C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows\build\downloads_cache\bison-2.4.1-lib.zip already exists. Skipping download.
INFO: Downloading "git" to "PortableGit-2.26.2-64-bit.7z.exe" ...
INFO: C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows\build\downloads_cache\PortableGit-2.26.2-64-bit.7z.exe already exists. Skipping download.
INFO: Downloading "gperf" to "gperf-3.0.1-bin.zip" ...
INFO: C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows\build\downloads_cache\gperf-3.0.1-bin.zip already exists. Skipping download.
INFO: Downloading "llvm" to "LLVM-10.0.0-win64.exe" ...
INFO: C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows\build\downloads_cache\LLVM-10.0.0-win64.exe already exists. Skipping download.
INFO: Downloading "ninja" to "ninja-win-1.9.0.zip" ...
INFO: C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows\build\downloads_cache\ninja-win-1.9.0.zip already exists. Skipping download.
INFO: Downloading "nodejs" to "node-v12.16.1-win-x64.zip" ...
INFO: C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows\build\downloads_cache\node-v12.16.1-win-x64.zip already exists. Skipping download.
INFO: Verifying hashes for "chromium" ...
INFO: Verifying hashes for "bison-bin" ...
INFO: Verifying hashes for "bison-dep" ...
INFO: Verifying hashes for "bison-lib" ...
INFO: Verifying hashes for "git" ...
INFO: Verifying hashes for "gperf" ...
INFO: Verifying hashes for "llvm" ...
INFO: Verifying hashes for "ninja" ...
INFO: Verifying hashes for "nodejs" ...
INFO: Unpacking downloads...
INFO: Unpacking "chromium" to ./ ...
Traceback (most recent call last):
  File "build.py", line 220, in <module>
    main()
  File "build.py", line 163, in main
    downloads.unpack_downloads(download_info, downloads_cache, source_tree, extractors)
  File "C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows\ungoogled-chromium\utils\downloads.py", line 314, in unpack_downloads
    extractor_func(
  File "C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows\ungoogled-chromium\utils\_extraction.py", line 225, in extract_tar_file
    _extract_tar_with_7z(sevenzip_bin, archive_path, output_dir, relative_to)
  File "C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows\ungoogled-chromium\utils\_extraction.py", line 118, in _extract_tar_with_7z
    _process_relative_to(output_dir, relative_to)
  File "C:\Users\Jonathan\Desktop\ChromiumBuild\ungoogled-chromium-windows\ungoogled-chromium\utils\_extraction.py", line 94, in _process_relative_to
    src_path.rename(dest_path)
  File "C:\Users\Jonathan\AppData\Local\Programs\Python\Python38-32\lib\pathlib.py", line 1358, in rename
    self._accessor.rename(self, target)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Jonathan\\Desktop\\ChromiumBuild\\ungoogled-chromium-windows\\build\\src\\chromium-83.0.4103.97\\.clang-format' -> 'C:\\Users\\Jonathan\\Desktop\\ChromiumBuild\\ungoogled-chromium-windows\\build\\src\\.clang-format'
```

Which I need to manually go and delete the src folder (this alone takes > 10 minutes because of the amount of files ~1million total files), and run build again.

Is there any way to tell the script to ignore files that already exist or overwrite them?

If not let me know, and I will close this issue. Just figured I'd ask :)

PS: Thank you for this project. I've finally found my end game browser. Cheers.

**Comment by Eloston** [comment]
> Is there any way to tell the script to ignore files that already exist or overwrite them?

If you'd like, feel free to add those features :)

The script is pretty dumb and assumes you're building from scratch every time. If you want to do a rebuild or resume a build, it's faster to invoke ninja yourself within an existing build tree (same command as in the build script, except you might need to set some environment variables).
