### ISSUE TITLE
devtools-frontend dom_extension.js build error

### ISSUE THREAD

**Issue by sailfish009** [Eloston/ungoogled-chromium#1132]
**Describe the bug**
devtools-frontend dom_extension.js build error

**To Reproduce**
1. cd /tmp/ungoogled-chromium/build/src
2. ninja -C out/Default chrome chromedriver chrome_sandbox
3. buil error message:
```
/tmp/ungoogled-chromium/build/src$ ninja -C out/Default chrome chromedriver chrome_sandbox
ninja: Entering directory `out/Default'
[51/28002] ACTION //third_party/devtools-frontend/src/front_end/dom_extension:dom_extension(//build/toolchain/linux:clang_x64)
FAILED: gen/third_party/devtools-frontend/src/front_end/dom_extension/dom_extension-tsconfig.json gen/third_party/devtools-frontend/src/front_end/dom_extension/dom_extension-tsconfig.json.tsbuildinfo gen/third_party/devtools-frontend/src/front_end/dom_extension/DOMExtension.js gen/third_party/devtools-frontend/src/front_end/dom_extension/DOMExtension.js.map gen/third_party/devtools-frontend/src/front_end/dom_extension/DOMExtension.d.ts gen/third_party/devtools-frontend/src/front_end/dom_extension/dom_extension.js gen/third_party/devtools-frontend/src/front_end/dom_extension/dom_extension.js.map gen/third_party/devtools-frontend/src/front_end/dom_extension/dom_extension.d.ts 
python ../../third_party/devtools-frontend/src/third_party/typescript/ts_library.py --tsconfig_output_location gen/third_party/devtools-frontend/src/front_end/dom_extension/dom_extension-tsconfig.json --front_end_directory ../../third_party/devtools-frontend/src/front_end/dom_extension --skip-lib-check --sources ../../third_party/devtools-frontend/src/front_end/dom_extension/DOMExtension.js ../../third_party/devtools-frontend/src/front_end/dom_extension/dom_extension.js
Traceback (most recent call last):
  File "../../third_party/devtools-frontend/src/third_party/typescript/ts_library.py", line 183, in <module>
    sys.exit(main())
  File "../../third_party/devtools-frontend/src/third_party/typescript/ts_library.py", line 108, in main
    found_errors, stderr = runTsc(tsconfig_location=tsconfig_output_location)
  File "../../third_party/devtools-frontend/src/third_party/typescript/ts_library.py", line 45, in runTsc
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[68/28002] CXX obj/components/crash/core/browser/browser/crashes_ui_util.o
ninja: build stopped: subcommand failed.
```

**Expected behavior**
build done

**Screenshots**
see build error message

**Environment (please complete the following information):**
 - OS/Platform and version: ubuntu 18.04 64bit
 - ungoogled-chromium version: latest git version (2020.08.13) 

**Additional context**
None.

**Comment by PF4Public** [comment]
Shouldn't you do `gn gen --args="…" out/Default` first?

**Comment by Eloston** [comment]
I am having troubles understanding your use-case. Please read https://github.com/Eloston/ungoogled-chromium/blob/master/docs/building.md. If you have additional questions, please let us know.

**Comment by sailfish009** [comment]
problem solved:
cd /tmp/ungoogled-chromium/build/src/third_party/node && ./update_node_binaries && cd -
