### ISSUE TITLE
Building AUR on Manjaro fails: Error in prepare()

### ISSUE THREAD

**Issue by ericschdt** [Eloston/ungoogled-chromium#1268]
**Describe the bug**
Building the AUR package on Manjaro fails.

**To Reproduce**
1. git clone https://aur.archlinux.org/ungoogled-chromium.git
2. cd ungoogled-chromium
3. makepkg -si

**Build log**
[build.log](https://github.com/Eloston/ungoogled-chromium/files/5612162/build.log)

**Last log lines**
```
patching file url/url_util.cc
Traceback (most recent call last):
  File "/path/to/AUR/ungoogled-chromium/src/ungoogled-chromium-87.0.4280.67-1/utils/patches.py", line 250, in <module>
    main()
  File "/path/to/AUR/ungoogled-chromium/src/ungoogled-chromium-87.0.4280.67-1/utils/patches.py", line 246, in main
    args.callback(args, parser.error)
  File "/path/to/AUR/ungoogled-chromium/src/ungoogled-chromium-87.0.4280.67-1/utils/patches.py", line 198, in _apply_callback
    apply_patches(
  File "/path/to/AUR/ungoogled-chromium/src/ungoogled-chromium-87.0.4280.67-1/utils/patches.py", line 132, in apply_patches
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/patch', '-p1', '--ignore-whitespace', '-i', '/path/to/AUR/ungoogled-chromium/src/ungoogled-chromium-87.0.4280.67-1/patches/core/ungoogled-chromium/block-trk-and-subdomains.patch', '-d', '.', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.
==> ERROR: Error happened in in prepare().
    Aborting...
```

**Environment (please complete the following information):**
 - OS/Platform and version: Manjaro
 - ungoogled-chromium version: 87.0.4280.67-1

**Comment by ericschdt** [comment]
Error seems to be gone with a clean build.
