### ISSUE TITLE
[92.0.4515.159] failed when running `gn.exe`

### ISSUE THREAD

**Issue by playgithub** [Eloston/ungoogled-chromium#1619]
## Env 
* OS: Windows
* IDE: Visual Studio 2019
* Windows 10 SDK: 10.0.20348.0
* Repo:  https://github.com/playgithub/ungoogled-chromium-windows Branch: 92.0.4515.159<br>forked from https://github.com/Nifury/ungoogled-chromium-windows Branch: v92.0.4515.131 @Nifury
## Log
```
D:\ungoogled-chromium-windows\build\src>call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" >nul

D:\ungoogled-chromium-windows\build\src>set DEPOT_TOOLS_WIN_TOOLCHAIN=0

D:\ungoogled-chromium-windows\build\src>"out\Default\gn.exe" "gen" "out\Default" "--fail-on-unused-args"
Traceback (most recent call last):
  File "D:\ungoogled-chromium-windows\build\src\build\toolchain\win\setup_toolchain.py", line 311, in <module>
    main()
  File "D:\ungoogled-chromium-windows\build\src\build\toolchain\win\setup_toolchain.py", line 271, in main
    vc_lib_um_path = FindFileInEnvList(env, 'LIB', ';', 'user32.lib')
  File "D:\ungoogled-chromium-windows\build\src\build\toolchain\win\setup_toolchain.py", line 209, in FindFileInEnvList
    assert optional, "%s is not found in %s:\n%s\nCheck if it is installed." % (
AssertionError: user32.lib is not found in LIB:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\lib\x64
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64
C:\Program Files (x86)\Windows Kits\10\lib\10.0.20348.0\ucrt\x64
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64
Check if it is installed.
ERROR at //build/config/win/BUILD.gn:298:27: Script returned non-zero exit code.
  vcvars_toolchain_data = exec_script("../../toolchain/win/setup_toolchain.py",
                          ^----------
Current dir: D:/ungoogled-chromium-windows/build/src/out/Default/
Command: C:/Users/alg/AppData/Local/Programs/Python/Python39/python3.exe D:/ungoogled-chromium-windows/build/src/build/toolchain/win/setup_toolchain.py "C:\Program Files (x86)/Microsoft Visual Studio/2019/Enterprise" "C:\Program Files (x86)\Windows Kits\10" "C:\Windows\System32;C:\Windows\SysWOW64;Arm64Unused" win x64 none
Returned 1.
See //build/config/BUILDCONFIG.gn:345:5: which caused the file to be included.
    "//build/config/win:lean_and_mean",
    ^---------------------------------
Traceback (most recent call last):
  File "D:\ungoogled-chromium-windows\build\src\build\toolchain\win\setup_toolchain.py", line 311, in <module>
    main()
  File "D:\ungoogled-chromium-windows\build\src\build\toolchain\win\setup_toolchain.py", line 271, in main
    vc_lib_um_path = FindFileInEnvList(env, 'LIB', ';', 'user32.lib')
  File "D:\ungoogled-chromium-windows\build\src\build\toolchain\win\setup_toolchain.py", line 209, in FindFileInEnvList
    assert optional, "%s is not found in %s:\n%s\nCheck if it is installed." % (
AssertionError: user32.lib is not found in LIB:
```

**Comment by playgithub** [comment]
Solved, Windows SDK version matters.
When failed, the output tells the version needed.
