### ISSUE TITLE
ninja: error: unknown target 'gn' 

### ISSUE THREAD

**Issue by lcosmos** [Eloston/ungoogled-chromium#1832]
$ ./tools/gn/bootstrap/bootstrap.py --skip-generate-buildfiles -j4 -o out/Default/
ninja: Entering directory `C:\ungoogled-chromium-97.0.4692.71-1\build\src\out\Release\gn_build'
ninja: error: unknown target 'gn'
Traceback (most recent call last):
  File "C:\ungoogled-chromium-97.0.4692.71-1\build\src\tools\gn\bootstrap\bootstrap.py", line 144, in <module>
    sys.exit(main(sys.argv[1:]))
  File "C:\ungoogled-chromium-97.0.4692.71-1\build\src\tools\gn\bootstrap\bootstrap.py", line 126, in main
    subprocess.check_call(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', 'C:\\ungoogled-chromium-97.0.4692.71-1\\build\\src\\out\\Release\\gn_build', '-w', 'dupbuild=err', '-j4', 'gn']' returned non-zero exit status 1.

**Comment by networkException** [comment]
Please follow the build instructions in https://github.com/ungoogled-software/ungoogled-chromium-windows and open an issue there if you encounter an issue

**Comment by Obaid51** [comment]
Facing the same issue when trying to rebuild after making changes in logos and name.
