### ISSUE TITLE
[macOS] Problems building 63

### ISSUE THREAD

**Issue by Eloston** [Eloston/ungoogled-chromium#321]
(Continuation of https://github.com/Eloston/ungoogled-chromium/issues/304#issuecomment-355594848)

@tectiv3 Where did you remove the clang flags? There may be some problem with the positioning of the arguments.

**Comment by tectiv3** [comment]
In `/build/sandbox/build/config/compiler/BUILD.gn`
```
  # TODO(hans): Remove this once Clang generates better optimized debug info by
  # default. https://crbug.com/765793
  if (is_clang && !is_nacl && current_toolchain == host_toolchain &&
      target_os != "chromeos") {
    cflags += [
      "-Xclang",
      "-mllvm",
      "-Xclang",
      "-instcombine-lower-dbg-declare=1",
    ]
  }
```
I removed 
```
      "-Xclang",
      "-instcombine-lower-dbg-declare=1",
```

**Comment by tectiv3** [comment]
I removed the whole block. It is building now.

**Comment by tectiv3** [comment]
Yep, built successfully.

**Comment by Eloston** [comment]
Closing until new building issues arise.

**Comment by Artur96** [comment]
I've pulled from `develop`, and generating build files fails on parsing:
```
Traceback (most recent call last):
  File "./utilikit/generate_build_files.py", line 118, in <module>
    _main()
  File "./utilikit/generate_build_files.py", line 115, in _main
    args.callback(resources, output_dir, args)
  File "./utilikit/generate_build_files.py", line 49, in _macos_callback
    args.apply_domain_substitution)
  File "/Users/Artur/ungoogled-chromium/utilikit/_build_files_generators/macos.py", line 55, in generate_build_files
    apply_domain_substitution)
  File "/Users/Artur/ungoogled-chromium/utilikit/export_resources.py", line 52, in export_patches_dir
    log_warnings=False)
  File "/Users/Artur/ungoogled-chromium/utilikit/substitute_domains.py", line 76, in substitute_domains_in_patches
    patchset = unidiff.PatchSet(file_obj.read())
  File "/Users/Artur/ungoogled-chromium/utilikit/_lib/unidiff/patch.py", line 353, in __init__
    self._parse(data, encoding=encoding)
  File "/Users/Artur/ungoogled-chromium/utilikit/_lib/unidiff/patch.py", line 399, in _parse
    current_file._parse_hunk(line, diff, encoding)
  File "/Users/Artur/ungoogled-chromium/utilikit/_lib/unidiff/patch.py", line 237, in _parse_hunk
    raise UnidiffParseError('Hunk diff line expected: %s' % line)
unidiff.errors.UnidiffParseError: Hunk diff line expected: @@ -724,6 +732,7 @@
```

**Comment by Eloston** [comment]
@tectiv3 It appears the changes you made to `ungoogled-chromium/macos/fix-gn-bootstrap.patch` in #322 created an invalid patch. Would you be able to fix that? Thanks

**Comment by tectiv3** [comment]
got it, don't understand why it happened. But will fix it.

**Comment by tectiv3** [comment]
Building now with ver.132

**Comment by tectiv3** [comment]
Built successfully. Crashpad bug still here.

**Comment by Eloston** [comment]
@tectiv3 If you're able to, I'll appreciate some input in #315
