### ISSUE TITLE
openSUSE15.0 KeyError: 'numbered_patch_list'

### ISSUE THREAD

**Issue by Aquarian-Age** [Eloston/ungoogled-chromium#539]
*If you have a problem, please fill out ALL the following fields.*

*Otherwise, please replace this template with your description.*

#### ungoogled-chromium version: FILL_HERE
```
[version]
chromium_version = 69.0.3497.100
release_revision = 2
```

#### Configuration and/or platform(s): FILL_HERE
```
Linux version 4.12.14-lp150.12.16-default (geeko@buildhost) (gcc version 7.3.1 20180323 [gcc-7-branch revision 258812] (SUSE Linux) ) #1 SMP Tue Aug 14 17:51:27 UTC 2018 (28574e6)

```

### Problem description

(python3.6.3) ~/src/ungoogled-chromium
日 9月 30|10:52 >./get_package.py opensuse build/src/ungoogled_packaging
Traceback (most recent call last):
  File "./get_package.py", line 230, in <module>
    main()
  File "./get_package.py", line 219, in main
    _process_templates(template_files, packaging_subs)
  File "./get_package.py", line 71, in _process_templates
    content = _BuildFileStringTemplate(new_file.read()).substitute(**build_file_subs)
  File "/home/xuan/.pyenv/versions/3.6.3/lib/python3.6/string.py", line 126, in substitute
    return self.pattern.sub(convert, self.template)
  File "/home/xuan/.pyenv/versions/3.6.3/lib/python3.6/string.py", line 119, in convert
    return str(mapping[named])
KeyError: 'numbered_patch_list'

**Comment by LeFroid** [comment]
You can use my fork of ungoogled chromium at https://github.com/LeFroid/ungoogled-chromium until I submit a PR. The latest release is working, I just haven't adapted the OpenSUSE config to conform with the new buildkit system yet.

**Comment by Aquarian-Age** [comment]
[2860/20013] clang++ -MMD -MF obj/sandbox/linux/sandbox_services/thread_helpers.o.d -DSANDBOX_IMPLEMENTATION -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DOFFICIAL_BUILD -DCHROMIUM_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_32 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_26 -I../.. -Igen -fprofile-sample-use=../../chrome/android/profiles/afdo.prof -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -no-canonical-prefixes -flto=thin -fwhole-program-vtables -m64 -march=x86-64 -Wall -Wextra -Wimplicit-fallthrough -Wthread-safety -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-address-of-packed-member -Wno-nonportable-include-path -Wno-user-defined-warnings -Wno-unused-lambda-capture -Wno-null-pointer-arithmetic -Wno-enum-compare-switch -Oz -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fsanitize=cfi-vcall -fsanitize-blacklist=../../tools/cfi/blacklist.txt -fsanitize=cfi-icall -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -isystem../../../../../../../usr/include/glib-2.0 -isystem../../../../../../../usr/lib64/glib-2.0/include -std=gnu++14 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../sandbox/linux/services/thread_helpers.cc -o obj/sandbox/linux/sandbox_services/thread_helpers.o
ninja: build stopped: subcommand failed.
