### ISSUE TITLE
Can't compile w/ arch linux

### ISSUE THREAD

**Issue by misaka00251** [Eloston/ungoogled-chromium#573]
I really don't know what problem is this. So I submitted on both [aur](https://aur.archlinux.org/packages/ungoogled-chromium/) and here.

## Console output and logs

```
...
The next patch would create the file third_party/ungoogled/BUILD.gn,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file third_party/ungoogled/ungoogled_switches.cc,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file third_party/ungoogled/ungoogled_switches.h,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
2018-10-27 23:29:33,502 - ERROR: Unexpected exception caught.
Traceback (most recent call last):
  File "/.../.../ungoogled-chromium/src/ungoogled-chromium-70.0.3538.77-1/buildkit/cli.py", line 384, in main
    args.callback(args=args)
  File "/.../.../ungoogled-chromium/src/ungoogled-chromium-70.0.3538.77-1/buildkit/cli.py", line 232, in _apply_callback
    patch_bin_path=args.patch_bin)
  File "/.../.../ungoogled-chromium/src/ungoogled-chromium-70.0.3538.77-1/buildkit/patches.py", line 95, in apply_patches
    subprocess.run(cmd, check=True)
  File "/usr/lib/python3.7/subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/patch', '-p1', '--ignore-whitespace', '-i', '/.../.../ungoogled-chromium/src/ungoogled-chromium-70.0.3538.77-1/patches/ungoogled-chromium/add-third-party-ungoogled.patch', '-d', '.', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.
``` 

## Environment details
ungoogled-chromium version: I uninstall it and this does not help.
Compiler toolchain: Python 3.7.1 & gcc 8.2.1 (probably)

**Comment by ian-moone** [comment]
```
...

The next patch would create the file third_party/ungoogled/BUILD.gn,
which already exists!  Skipping patch.

...
```

Try a fresh build; in a clean build tree.

**Comment by misaka00251** [comment]
It works!
