### ISSUE TITLE
Build fails on Windows 10

### ISSUE THREAD

**Issue by binaryh** [Eloston/ungoogled-chromium#582]
**Description**
Cant make the build process work under Windows 10.

**Console output and logs**

```
2018-11-04 00:41:11,771 - INFO: * Applying windows-disable-reorder-fix-linking.patch (116/123)
2018-11-04 00:41:11,772 - DEBUG: C:\Program Files\Git\usr\bin\patch.EXE -p1 --ignore-whitespace -i C:\Users\CK\Desktop\ungoogled-chromium-70.0.3538.77-1\build\src\ungoogled_packaging\patches\ungoogled-chromium\windows\windows-disable-reorder-fix-linking.patch -d C:\Users\CK\Desktop\ungoogled-chromium-70.0.3538.77-1\build\src --no-backup-if-mismatch --forward
patching file chrome/BUILD.gn
Hunk #3 succeeded at 306 (offset 5 lines).
patching file tools/perf/chrome_telemetry_build/BUILD.gn
Hunk #1 succeeded at 32 with fuzz 2 (offset -8 lines).
Hunk #2 FAILED at 104.
1 out of 2 hunks FAILED -- saving rejects to file tools/perf/chrome_telemetry_build/BUILD.gn.rej
patching file chrome/test/chromedriver/BUILD.gn
Hunk #1 succeeded at 357 with fuzz 1 (offset 9 lines).
Traceback (most recent call last):
  File "ungoogled_packaging\build.py", line 186, in <module>
    main()
  File "ungoogled_packaging\build.py", line 164, in main
    buildkit.patches.patch_paths_by_bundle(bundle), source_tree, patch_bin_path=None)
  File "C:\Users\CK\Desktop\ungoogled-chromium-70.0.3538.77-1\build\src\ungoogled_packaging\buildkit\patches.py", line 95, in apply_patches
    subprocess.run(cmd, check=True)
  File "C:\Users\CK\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Program Files\\Git\\usr\\bin\\patch.EXE', '-p1', '--ignore-whitespace', '-i', 'C:\\Users\\CK\\Desktop\\ungoogled-chromium-70.0.3538.77-1\\build\\src\\ungoogled_packaging\\patches\\ungoogled-chromium\\windows\\windows-disable-reorder-fix-linking.patch', '-d', 'C:\\Users\\CK\\Desktop\\ungoogled-chromium-70.0.3538.77-1\\build\\src', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.
```

**Environment details**

ungoogled-chromium version: 70.0.3538.77-1
Configuration bundle: windows
Packaging type (if applicable): windows
OS and version for building: Windows 10 64 bit
Compiler toolchain: ??

**Building and packaging steps**
- I followed the instructions from [building.md](https://github.com/Eloston/ungoogled-chromium/blob/master/docs/building.md#windows).

- Installed VS2017 with Windows SDK 10.0.17134.0 and VC++ ATL/MFC for x86 and x64 via the installer. - Activated debugging tools via control panel. 
- Installed python 2.7.15 and added it to system variables. 
- Installed python 3.7 and removed max path length.
- Downloaded  ungoogled-chromium version 70.0.3538.77-1 and unzipped it.
- Run the scripts:
> mkdir build\src
py get_package.py windows build\src\ungoogled_packaging
cd build\src
py ungoogled_packaging\build.py
py ungoogled_packaging\package.py

**Comment by Eloston** [comment]
See #475
