### ISSUE TITLE
Subsequent builds fail

### ISSUE THREAD

**Issue by kd7lxl** [Eloston/ungoogled-chromium#61]
This is somewhere between a usage question and a bug report.

When running build.py a second time, it fails due to `FileExistsError` when the tarfile module attempts to extract an archive that was extracted on a previous run. A primitive solution would be to `rm -rf build` before each run of `build.py`, but the build instructions do not indicate such a requirement. A more intelligent solution would be to check if the target already exists and is up to date, and if so, skip it.

```
2016-09-27 14:48:50,030 - INFO: Initialized default console logging handler
2016-09-27 14:48:50,030 - INFO: Using builder MacOSBuilder
2016-09-27 14:48:50,031 - INFO: Checking Python 2 command...
2016-09-27 14:48:50,031 - INFO: No Python 2 command specified; testing with 'python'
2016-09-27 14:48:50,099 - DEBUG: Using Python version '2.7.12'
2016-09-27 14:48:50,099 - INFO: Checking ninja command...
2016-09-27 14:48:50,105 - DEBUG: Using ninja version '1.7.1'
2016-09-27 14:48:50,105 - INFO: Checking quilt command...
2016-09-27 14:48:50,111 - DEBUG: Using quilt command '0.64'
2016-09-27 14:48:50,111 - INFO: Checking svn command...
2016-09-27 14:48:50,202 - DEBUG: Using svn command version '1.7.22'
2016-09-27 14:48:50,202 - INFO: Checking libtool command...
2016-09-27 14:48:50,203 - DEBUG: Found libtool at '/usr/bin/libtool'
2016-09-27 14:48:50,203 - INFO: Checking compilers...
2016-09-27 14:48:50,204 - INFO: build/downloads/chromium-53.0.2785.116.tar.xz already exists. Skipping download.
2016-09-27 14:48:50,204 - INFO: build/downloads/chromium-53.0.2785.116.tar.xz.hashes already exists. Skipping download.
2016-09-27 14:48:50,204 - INFO: Checking source archive integrity...
2016-09-27 14:48:50,204 - DEBUG: Running 'md5' hash check...
2016-09-27 14:48:51,293 - DEBUG: Running 'sha1' hash check...
2016-09-27 14:48:52,147 - DEBUG: Running 'sha224' hash check...
2016-09-27 14:48:53,627 - DEBUG: Running 'sha256' hash check...
2016-09-27 14:48:55,150 - DEBUG: Running 'sha384' hash check...
2016-09-27 14:48:56,273 - DEBUG: Running 'sha512' hash check...
2016-09-27 14:48:57,375 - INFO: Extracting source archive into building sandbox...
2016-09-27 14:48:57,375 - DEBUG: Appending resources/common/cleaning_list
2016-09-27 14:49:57,474 - ERROR: Exception thrown for tar member chromium-53.0.2785.116/tools/android/loading/cloud/frontend/common
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tarfile.py", line 2197, in makelink
    os.symlink(tarinfo.linkname, targetpath)
FileExistsError: [Errno 17] File exists: '../common' -> 'build/sandbox/tools/android/loading/cloud/frontend/common'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tarfile.py", line 2207, in makelink
    self._extract_member(self._find_link_target(tarinfo),
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tarfile.py", line 2370, in _find_link_target
    raise KeyError("linkname %r not found" % linkname)
KeyError: "linkname 'chromium-53.0.2785.116/tools/android/loading/cloud/frontend/../common' not found"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 57, in <module>
    exit(main())
  File "build.py", line 37, in main
    builder.setup_chromium_source()
  File "/Users/tom/src/ungoogled-chromium/buildlib/common.py", line 340, in setup_chromium_source
    "chromium-{}".format(self.chromium_version))
  File "/Users/tom/src/ungoogled-chromium/buildlib/_util.py", line 126, in extract_tar_file
    raise exc
  File "/Users/tom/src/ungoogled-chromium/buildlib/_util.py", line 123, in extract_tar_file
    tar_file_obj._extract_member(tarinfo, str(destination))
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tarfile.py", line 2116, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tarfile.py", line 2210, in makelink
    raise ExtractError("unable to resolve link inside archive")
tarfile.ExtractError: unable to resolve link inside archive
```
If this is intended behavior, I can submit a PR to update the docs to add the `rm -rf build` command.

**Comment by Eloston** [comment]
This exception is not intentional. Hopefully that commit fixes it. Let me know if it doesn't.

Though if you need to re-run the build, you should comment out the build steps you don't need to run in `build.py` before running it.

**Comment by kd7lxl** [comment]
Still same problem.

```
2016-09-27 20:49:16,581 - DEBUG: Appending resources/common/cleaning_list
2016-09-27 20:50:55,542 - ERROR: Exception thrown for tar member chromium-53.0.2785.116/third_party/skia/tools/gyp
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tarfile.py", line 2197, in makelink
    os.symlink(tarinfo.linkname, targetpath)
FileExistsError: [Errno 17] File exists: '../third_party/externals/gyp/' -> 'build/sandbox/third_party/skia/tools/gyp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tarfile.py", line 2207, in makelink
    self._extract_member(self._find_link_target(tarinfo),
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tarfile.py", line 2370, in _find_link_target
    raise KeyError("linkname %r not found" % linkname)
KeyError: "linkname 'chromium-53.0.2785.116/third_party/skia/tools/../third_party/externals/gyp/' not found"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 57, in <module>
    exit(main())
  File "build.py", line 37, in main
    builder.setup_chromium_source()
  File "/Users/tom/src/ungoogled-chromium/buildlib/common.py", line 357, in setup_chromium_source
    "chromium-{}".format(self.chromium_version))
  File "/Users/tom/src/ungoogled-chromium/buildlib/_util.py", line 128, in extract_tar_file
    raise exc
  File "/Users/tom/src/ungoogled-chromium/buildlib/_util.py", line 125, in extract_tar_file
    tar_file_obj._extract_member(tarinfo, str(destination)) # pylint: disable=protected-access
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tarfile.py", line 2116, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tarfile.py", line 2210, in makelink
    raise ExtractError("unable to resolve link inside archive")
tarfile.ExtractError: unable to resolve link inside archive
```
It's too bad tarfile doesn't have an overwrite option.
