### ISSUE TITLE
Build fails on Windows 10

### ISSUE THREAD

**Issue by yikjin** [Eloston/ungoogled-chromium#639]
### Description

Build fails on Windows 10 with error `subprocess.CalledProcessError: Command [...] returned non-zero exit status 1`. Similar to #582. Issue was supposedly solved in #475.

### Console output and logs

Full console output available [here](https://pastebin.com/LkiVwFBs).

```
Traceback (most recent call last):
  File "ungoogled_packaging\build.py", line 187, in <module>
    main()
  File "ungoogled_packaging\build.py", line 164, in main
    buildkit.patches.patch_paths_by_bundle(bundle), source_tree, patch_bin_path=None)
  File "C:\Users\marshmallow\Documents\GitHub\ungoogled-chromium\build\src\ungoogled_packaging\buildkit\patches.py", line 95, in apply_patches
    subprocess.run(cmd, check=True)
  File "C:\Users\marshmallow\Python 3.7.1\lib\subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\Users\\marshmallow\\Documents\\GitHub\\ungoogled-chromium\\build\\src\\third_party\\git\\usr\\bin\\patch.exe', '-p1', '--ignore-whitespace', '-i', 'C:\\Users\\marshmallow\\Documents\\GitHub\\ungoogled-chromium\\build\\src\\ungoogled_packaging\\patches\\ungoogled-chromium\\windows\\windows-fix-building-without-safebrowsing.patch', '-d', 'C:\\Users\\marshmallow\\Documents\\GitHub\\ungoogled-chromium\\build\\src', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.
```

### Environment details

* ungoogled-chromium version: `71.0.3578.98-2`
* Configuration bundle: `windows`
* Packaging type: `windows`
* OS and version for building: `Windows 10 (64-bit)`
* Compiler toolchain: `Visual Studio Community 2017 C++ tools`
  * Installed sub-components:
    * `Visual C++ core desktop features`
    * `Just-In-Time debugger`
    * `VC++ 2017 version 15.9 v14.16 latest v141 tools`
    * `C++ profiling tools`
    * `Windows 10 SDK (10.0.17763.0)`
    * `Visual C++ tools for CMake`
    * `Visual C++ ATL for x86 and x64`
    * `Test Adapter for Boost.Test`
    * `Test Adapter for Google Test`
    * `Visual C++ MFC for x86 and x64`

### Building and packaging steps

1. Install `Visual Studio Community 2017` with the above sub-components
2. Enable `Debugging Tools For Windows` for Windows 10 SDK
3. Install `Python 2.7.15`, `Python 3.7.1` and `7-Zip`
4. Run the command `pip install pypiwin32`
5. Set `PYTHON` user environment variable pointing to `Python 2.7.15`
6. Run the commands below in `ungoogled-chromium` Git repository in `cmd.exe` as administrator:
   
   ```cmd
   mkdir build\src
   py get_package.py windows build\src\ungoogled_packaging
   cd build\src
   py ungoogled_packaging\build.py
   ```

**Comment by hydrogenpi** [comment]
can someone create an OVA for the windows 64bit build of latest version 71.x and upload it?

**Comment by arturkomoter** [comment]
@hydrogenpi It's failing

**Comment by ahmedflix25** [comment]
same error

**Comment by TCB13** [comment]
Update:  `70.0.3538.110-3` fails differently:

````
>call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" >nul

C:\Users\TCB13\Desktop\ungoogled-chromium-70.0.3538.110-3\build\src>"out\Default\gn.exe" "gen" "out\Default" "--fail-on-unused-args"
Traceback (most recent call last):
  File "C:/Users/TCB13/Desktop/ungoogled-chromium-70.0.3538.110-3/build/src/build/vs_toolchain.py", line 471, in <module>
    sys.exit(main())
  File "C:/Users/TCB13/Desktop/ungoogled-chromium-70.0.3538.110-3/build/src/build/vs_toolchain.py", line 467, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "C:/Users/TCB13/Desktop/ungoogled-chromium-70.0.3538.110-3/build/src/build/vs_toolchain.py", line 442, in GetToolchainDir
    runtime_dll_dirs = SetEnvironmentAndGetRuntimeDllDirs()
  File "C:/Users/TCB13/Desktop/ungoogled-chromium-70.0.3538.110-3/build/src/build/vs_toolchain.py", line 45, in SetEnvironmentAndGetRuntimeDllDirs
    update_result = Update()
  File "C:/Users/TCB13/Desktop/ungoogled-chromium-70.0.3538.110-3/build/src/build/vs_toolchain.py", line 413, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Python27\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\Users\\TCB13\\Desktop\\ungoogled-chromium-70.0.3538.110-3\\build\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\Users\\TCB13\\Desktop\\ungoogled-chromium-70.0.3538.110-3\\build\\src\\build\\win_toolchain.json', '3bc0ec615cf20ee342f3bc29bc991b5ad66d8d2c']' returned non-zero exit status 1
ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
      exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
      ^----------
Current dir: C:/Users/TCB13/Desktop/ungoogled-chromium-70.0.3538.110-3/build/src/out/Default/
Command: C:/Python27/python.exe C:/Users/TCB13/Desktop/ungoogled-chromium-70.0.3538.110-3/build/src/build/vs_toolchain.py get_toolchain_dir
Returned 1 and printed out:




Please follow the instructions at https://chromium.9oo91esource.qjz9zk/chromium/src/+/master/docs/windows_build_instructions.md



See //third_party/angle/gni/angle.gni:79:3: whence it was imported.
  import("//build/config/win/visual_studio_version.gni")
  ^----------------------------------------------------
See //third_party/angle/src/tests/BUILD.gn:5:1: whence it was imported.
import("../../gni/angle.gni")
^---------------------------
See //BUILD.gn:203:7: which caused the file to be included.
      "//third_party/angle/src/tests:angle_unittests",
      ^----------------------------------------------

C:\Users\TCB13\Desktop\ungoogled-chromium-70.0.3538.110-3\build\src>exit
Traceback (most recent call last):
  File "ungoogled_packaging\build.py", line 186, in <module>
    main()
  File "ungoogled_packaging\build.py", line 178, in main
    _run_build_process('out\\Default\\gn.exe', 'gen', 'out\\Default', '--fail-on-unused-args')
  File "ungoogled_packaging\build.py", line 65, in _run_build_process
    **kwargs)
  File "C:\Program Files\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('cmd.exe', '/k')' returned non-zero exit status 1.
````

**Comment by arutr** [comment]
Apparently disabling the Safe Browsing patch seems to make the build work, according to [this](https://github.com/macchrome/winchrome/releases/tag/v72.0.3626.81-r612437-Win64).

**Comment by TCB13** [comment]
@arutr I'll try that solution, however if take a look at my log there are numerous patches that fail way before the one related to safe browsing.

**Comment by TCB13** [comment]
@arutr Disabling that patches seem to work, but I get the following toolchain error:

```
C:\Users\TCB13\Desktop\ungoogled-chromium-71.0.3578.98-2\build\src>"out\Default\gn.exe" "gen" "out\Default" "--fail-on-unused-args"
Traceback (most recent call last):
  File "C:/Users/TCB13/Desktop/ungoogled-chromium-71.0.3578.98-2/build/src/build/vs_toolchain.py", line 468, in <module>    sys.exit(main())
  File "C:/Users/TCB13/Desktop/ungoogled-chromium-71.0.3578.98-2/build/src/build/vs_toolchain.py", line 464, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "C:/Users/TCB13/Desktop/ungoogled-chromium-71.0.3578.98-2/build/src/build/vs_toolchain.py", line 439, in GetToolchainDir
    runtime_dll_dirs = SetEnvironmentAndGetRuntimeDllDirs()
  File "C:/Users/TCB13/Desktop/ungoogled-chromium-71.0.3578.98-2/build/src/build/vs_toolchain.py", line 42, in SetEnvironmentAndGetRuntimeDllDirs
    update_result = Update()
  File "C:/Users/TCB13/Desktop/ungoogled-chromium-71.0.3578.98-2/build/src/build/vs_toolchain.py", line 410, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Python27\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\Users\\TCB13\\Desktop\\ungoogled-chromium-71.0.3578.98-2\\build\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\Users\\TCB13\\Desktop\\ungoogled-chromium-71.0.3578.98-2\\build\\src\\build\\win_toolchain.json', '3bc0ec615cf20ee342f3bc29bc991b5ad66d8d2c']' returned non-zero exit status 1
ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
      exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
      ^----------
Current dir: C:/Users/TCB13/Desktop/ungoogled-chromium-71.0.3578.98-2/build/src/out/Default/
Command: C:/Python27/python.exe C:/Users/TCB13/Desktop/ungoogled-chromium-71.0.3578.98-2/build/src/build/vs_toolchain.py get_toolchain_dir
Returned 1 and printed out:




Please follow the instructions at https://chromium.9oo91esource.qjz9zk/chromium/src/+/master/docs/windows_build_instructions.md



See //third_party/angle/gni/angle.gni:80:3: whence it was imported.
  import("//build/config/win/visual_studio_version.gni")
  ^----------------------------------------------------
See //third_party/angle/src/tests/BUILD.gn:5:1: whence it was imported.
import("../../gni/angle.gni")
^---------------------------
See //BUILD.gn:202:7: which caused the file to be included.
      "//third_party/angle/src/tests:angle_white_box_tests",
      ^----------------------------------------------------

C:\Users\TCB13\Desktop\ungoogled-chromium-71.0.3578.98-2\build\src>exit
Traceback (most recent call last):
  File "ungoogled_packaging\build.py", line 187, in <module>
    main()
  File "ungoogled_packaging\build.py", line 179, in main
    _run_build_process('out\\Default\\gn.exe', 'gen', 'out\\Default', '--fail-on-unused-args')
  File "ungoogled_packaging\build.py", line 65, in _run_build_process
    **kwargs)
  File "C:\Program Files\Python36\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('cmd.exe', '/k')' returned non-zero exit status 1.
```

**Comment by TCB13** [comment]
**Update**: I manage get around the errors above by reinstalling Python 3 and Python 2 and depot_tools from https://storage.googleapis.com/chrome-infra/depot_tools.zip (as explained here https://chromium.googlesource.com/chromium/src/+/64.0.3282.168/docs/windows_build_instructions.md#install).

After this I was able to proceed with the build until I hit...

```
In file included from ../..\third_party/skia/include/core/../private/SkOnce.h:13:
../..\third_party/skia/include/core/SkTypes.h(13,10):  fatal error: 'SkUserConfig.h' file not found
#include "SkUserConfig.h"
         ^~~~~~~~~~~~~~~~
```

**Comment by TCB13** [comment]
Looks like I'm not properly disabling the safe browser, how am I supposed to do that?

**Comment by TN0X** [comment]
> 4\. Disable safe-browsing patches by:
> 
> * Search in the folder `C:\ungoogled-chromium-71.0.3578.98-2\patches` for `safe` and delete all files related to safe search

you dont have to delete any files. Only edit the patch.list and gn_flags.map files


> 8. Run:
> 
> ```
> mkdir build\src
> py get_package.py windows build\src\ungoogled_packaging
> cd build\src
> ```
> 9. Search once again for `safe` inside `build\src` and also remove any files there
> 10. Finally build by running `py ungoogled_packaging\build.py`

Step 9. is not neccessary, because step 8. copies your changes in step 7. into build\src\ungoogled_packaging. 

Here the steps for the build process of ungoogled-chromium 71.0.3578.98-2:

1. checkout tagged version 71.0.3578.98-2 of ungoogled-chromium

2. delete build/src folder completely (after prior build process)

3. edit like described for deleting all "safe-browsing" references:
config_bundles\windows\patch_order.list
config_bundles\common\patch_order.list
config_bundles\common\gn_flags.map

3. Run
`mkdir build\src`
`py get_package.py windows build\src\ungoogled_packaging`
`cd build\src`
`py ungoogled_packaging\build.py`
`py ungoogled_packaging\package.py`

thats all

**Comment by TCB13** [comment]
@TN0X should I worry about this error?
````
[546/20133] ACTION //chrome/test/chromedriver:embed_version_in_cpp(//build/toolchain/win:win_clang_x64)
ERROR:root:Git error: rc=0, output='
````

**Comment by TN0X** [comment]
> @TN0X should I worry about this error?
> 
> ```
> [546/20133] ACTION //chrome/test/chromedriver:embed_version_in_cpp(//build/toolchain/win:win_clang_x64)
> ERROR:root:Git error: rc=0, output='
> ``
No, I got the same error at this point.

**Comment by TCB13** [comment]
@TN0X I finally managed to get a working build!! Only possible with your precious help!

I did a few things differently this way:

1. Used PowerShell instead of cmd.exe to compile it
2. I was downloading the tag as a zip from github, this time I did:
````
git clone https://github.com/Eloston/ungoogled-chromium.git
git checkout tags/71.0.3578.98-2
````
Not sure if there was some issue with that zip download or the path in my computer was way too big, because it used to be `C:\ungoogled-chromium\71.0.3578.98-2` and this time, it was just `C:\ungoogled-chromium`.

Thank you very much for all your help!

**Comment by intika** [comment]
safe-browsing patches needs to be updated for windows, i will see what i can do ;)

**Comment by intika** [comment]
i guess this would be solved here https://github.com/Eloston/ungoogled-chromium/issues/619 later on 
@Eloston

**Comment by Eloston** [comment]
Closing per @intika's request.
