### ISSUE TITLE
fails on macos/fix-gn-safe_browsing.patch

### ISSUE THREAD

**Issue by pouledodue** [Eloston/ungoogled-chromium#672]
### Description

`./ungoogled_packaging/build.sh` fails

### Console output and logs

```
2019-02-09 09:31:54,656 - INFO: * Applying fix-gn-safe_browsing.patch (117/121)
2019-02-09 09:31:54,656 - DEBUG: /usr/bin/patch -p1 --ignore-whitespace -i /Users/pouledodue/github/ungoogled-chromium/build/src/ungoogled_packaging/patches/ungoogled-chromium/macos/fix-gn-safe_browsing.patch -d .. --no-backup-if-mismatch --forward
patching file build/config/compiler/BUILD.gn
Hunk #1 FAILED at 1497.
1 out of 1 hunk FAILED -- saving rejects to file build/config/compiler/BUILD.gn.rej
patching file chrome/browser/BUILD.gn
Hunk #1 succeeded at 1742 (offset 13 lines).
patching file chrome/browser/extensions/BUILD.gn
Hunk #1 succeeded at 775 (offset -1 lines).
patching file chrome/browser/ui/BUILD.gn
Hunk #1 succeeded at 384 with fuzz 2 (offset 3 lines).
patching file chrome/browser/ui/webui/settings/change_password_handler.cc
2019-02-09 09:31:54,671 - ERROR: Unexpected exception caught.
Traceback (most recent call last):
  File "/Users/pouledodue/github/ungoogled-chromium/build/src/ungoogled_packaging/buildkit/cli.py", line 384, in main
    args.callback(args=args)
  File "/Users/pouledodue/github/ungoogled-chromium/build/src/ungoogled_packaging/buildkit/cli.py", line 232, in _apply_callback
    patch_bin_path=args.patch_bin)
  File "/Users/pouledodue/github/ungoogled-chromium/build/src/ungoogled_packaging/buildkit/patches.py", line 95, in apply_patches
    subprocess.run(cmd, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/patch', '-p1', '--ignore-whitespace', '-i', '/Users/pouledodue/github/ungoogled-chromium/build/src/ungoogled_packaging/patches/ungoogled-chromium/macos/fix-gn-safe_browsing.patch', '-d', '..', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.
```

### Environment details

* ungoogled-chromium version: chromium-72.0.3626.81.tar.xz
* Configuration bundle: macos
* Packaging type (if applicable): macos
* OS and version for building: Mojave
* Compiler toolchain: Xcode 10.0

*(If relevant, add other environment details here)*

### Building and packaging steps

```
# Run from inside the clone of the repository
mkdir -p build/src/ungoogled_packaging
./get_package.py macos build/src/ungoogled_packaging
cd build/src
./ungoogled_packaging/build.sh
```

**Comment by Eloston** [comment]
Patches haven't been updated yet for macOS. This error is expected. You can see the status of patches in the validate_patches CI task in commits, [like this one](https://github.com/Eloston/ungoogled-chromium/runs/61780678).
