### ISSUE TITLE
Python 2 problems on Arch Linux

### ISSUE THREAD

**Issue by sjug** [Eloston/ungoogled-chromium#68]
Goes off and does a whole lot of patching until:

```
Now at patch ../patches/ungoogled-chromium/remove-get-help-button.patch
2016-09-29 16:58:58,672 - INFO: Running gyp command...
2016-09-29 16:58:58,673 - DEBUG: Appending resources/common/gyp_flags
2016-09-29 16:58:58,673 - DEBUG: Appending resources/linux_static/gyp_flags
2016-09-29 16:58:58,673 - DEBUG: GYP command: build/gyp_chromium --depth=. --check -Denable_rlz=0 -Duse_official_google_api_keys=0 -Dproprietary_codecs=1 -Dfieldtrial_testing_like_official_build=1 -Denable_hangout_services_extension=0 -Ddisable_newlib=1 -Denable_webrtc=0 -Dremoting=0 -Ddefault_apps_list_linux_dest=[] -Ddisable_nacl=1 -Dtracing_like_official_build=1 -Ddisable_fatal_linker_warnings=1 -Denable_prod_wallet_service=0 -Denable_google_now=0 -Denable_automation=0 -Denable_one_click_signin=0 -Dremove_webcore_debug_symbols=1 -Ddisable_pnacl=1 -Dbuildtype=Official -Dwerror= -Denable_hotwording=0 -Denable_pre_sync_backup=0 -Dffmpeg_branding=Chrome -Dfastbuild=2 -Dlinux_strip_binary=1 -Denable_hidpi=1 -Denable_wifi_bootstrapping=0 -Denable_remoting_host=0 -Ddefault_apps_list=[] -Dsafe_browsing=0
Traceback (most recent call last):
  File "build/gyp_chromium", line 12, in <module>
    execfile(__file__ + '.py')
NameError: name 'execfile' is not defined
2016-09-29 16:58:58,694 - ERROR: GYP command returned non-zero exit code: 1
```

Any more info I can provide to help debug?

**Comment by Eloston** [comment]
Does `/usr/bin/env python` resolve to Python 3 on Arch Linux? If so, you'll need to set `builder.python2_command` to be the command to launch Python 2.

**Comment by sakaru** [comment]
Seems this is a python3/python2 thing, see https://github.com/Eloston/ungoogled-chromium/issues/68

**Comment by sjug** [comment]
@Eloston how do I pass the python2_command?

**Comment by Eloston** [comment]
You need to edit `build.py` and set the attribute where the code comment says to.

**Comment by sjug** [comment]
Yeah I had done that in order to get past the error early on `Checking Python 2 command...`
I was just wondering if there was another way to do it.

I'm seeing that error with it set to `python2` which is correct.

**Comment by Eloston** [comment]
That's strange. Setting `builder.python2_command = "python2"` works as expected on my system.

BTW, are you using a tagged version or the master branch?

**Comment by sjug** [comment]
Just building straight off master, I'll try a tag.

**Comment by Eloston** [comment]
You probably don't want to use a tag because the latest tag doesn't implement static Linux builds; it falls back to a Debian builder.

**Comment by sjug** [comment]
I was just about to say it's failing with DebianBuilder errors.

**Comment by Eloston** [comment]
What does your `build.py` look like right now?

**Comment by sjug** [comment]
It's unmodified just the `buildlib/common.py` has the python2_command set.

**Comment by sjug** [comment]
Did a fresh build and it dies on: 

```
Now at patch ../patches/ungoogled-chromium/remove-get-help-button.patch
2016-09-29 18:58:54,281 - INFO: Running gyp command...
2016-09-29 18:58:54,281 - DEBUG: Appending resources/common/gyp_flags
2016-09-29 18:58:54,282 - DEBUG: Appending resources/linux_static/gyp_flags
2016-09-29 18:58:54,282 - DEBUG: GYP command: python2 build/gyp_chromium --depth=. --check -Dtracing_like_official_build=1 -Ddefault_apps_list=[] -Denable_hotwording=0 -Dremoting=0 -Dsafe_browsing=0 -Ddefault_apps_list_linux_dest=[] -Denable_wifi_bootstrapping=0 -Denable_pre_sync_backup=0 -Dfieldtrial_testing_like_official_build=1 -Dwerror= -Ddisable_nacl=1 -Ddisable_fatal_linker_warnings=1 -Denable_hangout_services_extension=0 -Dfastbuild=2 -Denable_hidpi=1 -Denable_google_now=0 -Dproprietary_codecs=1 -Ddisable_newlib=1 -Denable_rlz=0 -Denable_automation=0 -Dbuildtype=Official -Dffmpeg_branding=Chrome -Ddisable_pnacl=1 -Dlinux_strip_binary=1 -Denable_remoting_host=0 -Denable_one_click_signin=0 -Dremove_webcore_debug_symbols=1 -Denable_webrtc=0 -Duse_official_google_api_keys=0 -Denable_prod_wallet_service=0
Updating projects from gyp files...
  File "../tools/clang/scripts/update.py", line 121
    print ' Done.'
                 ^
SyntaxError: Missing parentheses in call to 'print'
gyp: Call to 'python ../tools/clang/scripts/update.py --print-revision' returned exit status 1 while in /home/user/ungoogled-chromium/build/sandbox/build/all.gyp.
2016-09-29 18:58:57,337 - ERROR: GYP command returned non-zero exit code: 1
```

**Comment by Eloston** [comment]
[Looks like Inox had to do some workarounds too](https://github.com/gcarq/inox-patchset/blob/master/PKGBUILD#L141). Solving #69 should fix this issue.

**Comment by Eloston** [comment]
Hopefully that commit does it. Let me know if it doesn't.

**Comment by pickfire** [comment]
@Eloston I still find error building with python2 or python3:

### python2
```
  File "build.py", line 50
    print("ERROR: {!s}".format(exc), file=sys.stderr)
                                         ^
SyntaxError: invalid syntax
```

### python3
```
Now at patch ../patches/ungoogled-chromium/fix-building-with-iridium-trknotify.patch
2016-10-19 10:25:39,381 - INFO: Running gyp command...
2016-10-19 10:25:39,382 - DEBUG: Appending resources/common/gyp_flags
2016-10-19 10:25:39,382 - DEBUG: GYP command: build/gyp_chromium --depth=. --check -Dlinux_strip_binary=1
-Ddisable_nacl=1 -Denable_pre_sync_backup=0 -Dtracing_like_official_build=1 -Dremove_webcore_debug_symbols=1 -Denable_remoting_host=0 -Denable_rlz=0 -Denable_hidpi=1 -Dffmpeg_branding=Chrome -Denable_google_now=0 -Ddefault_apps_list_linux_dest=[] -Ddisable_pnacl=1 -Dproprietary_codecs=1 -Denable_hotwording=0 -Ddisable_newlib=1 -Dsafe_browsing=0 -Denable_webrtc=0 -Denable_automation=0 -Denable_prod_wallet_service=0 -Duse_official_google_api_keys=0 -Ddisable_fatal_linker_warnings=1 -Ddefault_apps_list=[] -Denable_one_click_signin=0 -Denable_wifi_bootstrapping=0 -Dwerror= -Dfieldtrial_testing_like_official_build=1 -Denable_hangout_services_extension=0 -Dremoting=0 -Dfastbuild=2
Traceback (most recent call last):
  File "build/gyp_chromium", line 12, in <module>
    execfile(__file__ + '.py')
NameError: name 'execfile' is not defined
2016-10-19 10:25:39,431 - ERROR: GYP command returned non-zero exit code: 1
```

**Comment by Eloston** [comment]
@pickfire Could you try setting python2_command to `python`?

**Comment by sjug** [comment]
I see the same error as @pickfire.
After setting python2_command to `python` then I get this error:

```
Now at patch ../patches/ungoogled-chromium/fix-building-with-iridium-trknotify.patch
2016-10-20 06:07:03,608 - INFO: Running gyp command...
2016-10-20 06:07:03,608 - DEBUG: Appending resources/common/gyp_flags
2016-10-20 06:07:03,608 - DEBUG: GYP command: python build/gyp_chromium --depth=. --check -Dfastbuild=2 -Ddisable_pnacl=1 -Dremove_webcore_debug_symbols=1 -Dproprietary_codecs=1 -Dremoting=0 -Denable_one_click_signin=0 -Denable_remoting_host=0 -Denable_google_now=0 -Denable_rlz=0 -Dffmpeg_branding=Chrome -Ddisable_nacl=1 -Denable_automation=0 -Denable_hotwording=0 -Ddisable_fatal_linker_warnings=1 -Ddefault_apps_list_linux_dest=[] -Denable_webrtc=0 -Duse_official_google_api_keys=0 -Denable_hangout_services_extension=0 -Denable_prod_wallet_service=0 -Dtracing_like_official_build=1 -Dsafe_browsing=0 -Dfieldtrial_testing_like_official_build=1 -Denable_pre_sync_backup=0 -Denable_wifi_bootstrapping=0 -Dlinux_strip_binary=1 -Denable_hidpi=1 -Ddefault_apps_list=[] -Ddisable_newlib=1 -Dwerror=
Traceback (most recent call last):
  File "build/gyp_chromium", line 12, in <module>
    execfile(__file__ + '.py')
NameError: name 'execfile' is not defined
2016-10-20 06:07:03,629 - ERROR: GYP command returned non-zero exit code: 1
```

**Comment by pickfire** [comment]
Yeah, I get the same outcome too.

**Comment by Eloston** [comment]
Do you have a file named `python` in `build/path_overrides`?

**Comment by pickfire** [comment]
@Eloston Seems so.

**Comment by Eloston** [comment]
Is there anything in it?

**Comment by pickfire** [comment]
Yup, shell but instead it said bash:
```sh
#!/bin/bash
python2 "$@"
```

**Comment by Eloston** [comment]
That's strange, because path overrides work on my system. Does `python2` not launch Python 2 on your system?

**Comment by pickfire** [comment]
@Eloston `python2` does launch python 2, but using `python2 build.py` doesn't even work like I said.

**Comment by Eloston** [comment]
Wait. Why are you setting `python2_command` to `python`? That's Python 3 isn't it? Try setting it to `python2`.

Also `buildlib` only works with Python 3, it says so in the docs too.

**Comment by pickfire** [comment]
@Eloston I am a bit confused now. So we are supposed to `python3 build.py` but then we need to set `python_command = "python2"`? Still I have some problems with missing parenthesis if I run `python3 build.py`:
```
Updating projects from gyp files...
  File "../tools/clang/scripts/update.py", line 121
    print ' Done.'
                 ^
SyntaxError: Missing parentheses in call to 'print'
gyp: Call to 'python ../tools/clang/scripts/update.py --print-revision' returned exit status 1 while in /home/ivan/src/ungoogled-chromium/build/sandbox/build/all.gyp.
2016-10-21 17:37:52,068 - ERROR: GYP command returned non-zero exit code: 1
```
But then if I `python2 build.py`:
```
  File "build.py", line 50
    print("ERROR: {!s}".format(exc), file=sys.stderr)
                                         ^
SyntaxError: invalid syntax
```

**Comment by pickfire** [comment]
@Eloston Still same thing happened:
```
Updating projects from gyp files...
  File "../tools/clang/scripts/update.py", line 121
    print ' Done.'
                 ^
SyntaxError: Missing parentheses in call to 'print'
gyp: Call to 'python ../tools/clang/scripts/update.py --print-revision' returned exit status 1 while in /home/ivan/src/ungoogled-chromium/build/sandbox/build/all.gyp.
2016-10-22 17:45:27,591 - ERROR: GYP command returned non-zero exit code: 1
```

**Comment by pickfire** [comment]
Weird, what is these errors, I think it's not related to the python script now:
```
Now at patch ../patches/ungoogled-chromium/fix-building-with-iridium-trknotify.patch
2016-10-23 23:01:07,275 - INFO: Running gyp command...
2016-10-23 23:01:07,276 - DEBUG: Appending resources/common/gyp_flags
2016-10-23 23:01:07,277 - DEBUG: GYP command: python2 build/gyp_chromium --depth=. --check -Dproprietary_codecs=1 -Ddisable_fatal_linker_warnings=1 -Ddefault_apps_list_linux_dest=[] -Denable_webrtc=0 -Dtracing_like_official_build=1 -Dwerror= -Denable_hidpi=1 -Dffmpeg_branding=Chrome -Dremoting=0 -Denable_hotwording=0 -Dfieldtrial_testing_like_official_build=1 -Ddisable_pnacl=1 -Denable_automation=0 -Dremove_webcore_debug_symbols=1 -Duse_official_google_api_keys=0 -Ddisable_nacl=1 -Dsafe_browsing=0 -Denable_rlz=0 -Denable_wifi_bootstrapping=0 -Ddisable_newlib=1 -Denable_hangout_services_extension=0 -Denable_pre_sync_backup=0 -Denable_prod_wallet_service=0 -Denable_one_click_signin=0 -Ddefault_apps_list=[] -Dfastbuild=2 -Denable_remoting_host=0 -Denable_google_now=0 -Dlinux_strip_binary=1
Updating projects from gyp files...
gyp: Call to 'python cups_config_helper.py --api-version /home/ivan/src/ungoogled-chromium/build/sandbox/build/linux/debian_wheezy_amd64-sysroot' returned exit status 1 while in /home/ivan/src/ungoogled-chromium/build/sandbox/printing/printing.gyp.
Package libpulse was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpulse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpulse' found
Package libpulse was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpulse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpulse' found
gyp: Call to '../build/linux/pkg-config-wrapper "/home/ivan/src/ungoogled-chromium/build/sandbox/build/linux/debian_wheezy_amd64-sysroot" "x64" "lib" --cflags libpulse' returned exit status 1 while in /home/ivan/src/ungoogled-chromium/build/sandbox/media/media.gyp.
Package atk was not found in the pkg-config search path.
Perhaps you should add the directory containing `atk.pc'
to the PKG_CONFIG_PATH environment variable
No package 'atk' found
Package atk was not found in the pkg-config search path.
Perhaps you should add the directory containing `atk.pc'
to the PKG_CONFIG_PATH environment variable
No package 'atk' found
gyp: Call to '../../build/linux/pkg-config-wrapper "/home/ivan/src/ungoogled-chromium/build/sandbox/build/linux/debian_wheezy_amd64-sysroot" "x64" "lib" --cflags atk' returned exit status 1 while in /home/ivan/src/ungoogled-chromium/build/sandbox/build/linux/system.gyp.
2016-10-23 23:01:35,618 - ERROR: GYP command returned non-zero exit code: 1
```
I am sure that I have installed `atk` and `libpulse`.
