### ISSUE TITLE
[Windows] Assertion failed bug

### ISSUE THREAD

**Issue by Kieaer** [Eloston/ungoogled-chromium#788]
**Describe the bug**
When build on Windows 10, get an Assertion failed bug error.

**To Reproduce**
1. Clone ungoogled-chromium-windows
2. install python2, python3, visual studio and more... set build environments.
3. open cmd and enter "py build.py" command

**Expected behavior**
Build successful

**Screenshots**
none.

**Environment (please complete the following information):**
 - OS/Platform and version: Windows 10 Pro 1903
 - ungoogled-chromium version: Unknown (No version here)

**Additional context**
```
참고: 포함 파일: C:\Users\cloud\source\repos\ungoogled-chromium-windows\build\src\tools\gn\tools/gn/trace.h
참고: 포함 파일:  C:\Users\cloud\source\repos\ungoogled-chromium-windows\build\src\tools\gn\util/ticks.h
[175/175] LINK gn.exe
코드를 생성하고 있습니다.
코드를 생성했습니다.

C:\Users\cloud\source\repos\ungoogled-chromium-windows\build\src>exit
C:\Users\cloud\source\repos\ungoogled-chromium-windows\build\src>call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat" >nul

C:\Users\cloud\source\repos\ungoogled-chromium-windows\build\src>"out\Default\gn.exe" "gen" "out\Default" "--fail-on-unused-args"
ERROR at //tools/grit/grit_rule.gni:101:3: Assertion failed.
  assert(
  ^-----
resource whitelist generation only works on non-component builds with debug info enabled.
See //tools/grit/grit_rule.gni:102:7:
      symbol_level > 0 && !strip_debug_info && !is_component_build,
      ^-----------------------------------------------------------
This is where it was set.
See //net/BUILD.gn:16:1: whence it was imported.
import("//tools/grit/grit_rule.gni")
^----------------------------------
See //BUILD.gn:113:7: which caused the file to be included.
      "//net:hpack_example_generator",
      ^------------------------------
Toolchain is out of date. Run "gclient runhooks" to update the toolchain, or set DEPOT_TOOLS_WIN_TOOLCHAIN=0 to use the locally installed toolchain.
Traceback (most recent call last):
  File "C:/Users/cloud/source/repos/ungoogled-chromium-windows/build/src/build/vs_toolchain.py", line 509, in <module>
    sys.exit(main())
  File "C:/Users/cloud/source/repos/ungoogled-chromium-windows/build/src/build/vs_toolchain.py", line 505, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "C:/Users/cloud/source/repos/ungoogled-chromium-windows/build/src/build/vs_toolchain.py", line 480, in GetToolchainDir
    runtime_dll_dirs = SetEnvironmentAndGetRuntimeDllDirs()
  File "C:/Users/cloud/source/repos/ungoogled-chromium-windows/build/src/build/vs_toolchain.py", line 48, in SetEnvironmentAndGetRuntimeDllDirs
    update_result = Update(no_download=True)
  File "C:/Users/cloud/source/repos/ungoogled-chromium-windows/build/src/build/vs_toolchain.py", line 451, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Python27\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\Users\\cloud\\source\\repos\\ungoogled-chromium-windows\\build\\src\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\Users\\cloud\\source\\repos\\ungoogled-chromium-windows\\build\\src\\build\\win_toolchain.json', '818a152b3f1da991c1725d85be19a0f27af6bab4', '--no-download']' returned non-zero exit status 1

C:\Users\cloud\source\repos\ungoogled-chromium-windows\build\src>exit
Traceback (most recent call last):
  File "build.py", line 210, in <module>
    main()
  File "build.py", line 202, in main
    _run_build_process('out\\Default\\gn.exe', 'gen', 'out\\Default', '--fail-on-unused-args')
  File "build.py", line 67, in _run_build_process
    **kwargs)
  File "C:\Users\cloud\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('cmd.exe', '/k')' returned non-zero exit status 1.

C:\Users\cloud\source\repos\ungoogled-chromium-windows>
```

**Comment by r4sas** [comment]
Help needed: https://github.com/ungoogled-software/ungoogled-chromium-windows/issues/2
