### ISSUE TITLE
Step 5 ==> "No such file or directory"

### ISSUE THREAD

**Issue by GildedHonour** [Eloston/ungoogled-chromium#881]
When running the last command from the step 5, I get an error:

5. Build GN:
```

mkdir -p build/src/out/Default
cp flags.gn build/src/out/Default/args.gn
cd build/src

# here
./tools/gn/bootstrap/bootstrap.py --skip-generate-buildfiles -j4 -o out/Default/gn
```

==>

```
Traceback (most recent call last):
  File "./tools/gn/bootstrap/bootstrap.py", line 142, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./tools/gn/bootstrap/bootstrap.py", line 125, in main
    ['ninja', '-C', gn_build_dir, 'gn', '-w', 'dupbuild=err', '-j'+str(options.jobs)])
  File "/usr/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by GildedHonour** [comment]
This doesn't this it

```
mkdir -p out/Default/gn_build
```
