### ISSUE TITLE
Error running utils/patches.py

### ISSUE THREAD

**Issue by wizeman** [Eloston/ungoogled-chromium#971]
**Describe the bug**

There seems to be a bug in new code that was recently added to `utils/patches.py`.
It used to work fine before but now it fails with the following error:

```
ERROR: 18 files could not be pruned.
some errors
INFO: Applying patches from /nix/store/i2ky6jiphp98mlxcc7z7ayr7rgi20z8b-ungoogled-chromium-80.0.3987.149-1/patches
Traceback (most recent call last):
  File "/nix/store/i2ky6jiphp98mlxcc7z7ayr7rgi20z8b-ungoogled-chromium-80.0.3987.149-1/utils/.patches.py-wrapped", line 236, in <module>
    main()
  File "/nix/store/i2ky6jiphp98mlxcc7z7ayr7rgi20z8b-ungoogled-chromium-80.0.3987.149-1/utils/.patches.py-wrapped", line 232, in main
    args.callback(args)
  File "/nix/store/i2ky6jiphp98mlxcc7z7ayr7rgi20z8b-ungoogled-chromium-80.0.3987.149-1/utils/.patches.py-wrapped", line 189, in _apply_callback
    patch_bin_path=args.patch_bin)
  File "/nix/store/i2ky6jiphp98mlxcc7z7ayr7rgi20z8b-ungoogled-chromium-80.0.3987.149-1/utils/.patches.py-wrapped", line 111, in apply_patches
    patch_bin_path = find_and_check_patch(patch_bin_path=patch_bin_path)
  File "/nix/store/i2ky6jiphp98mlxcc7z7ayr7rgi20z8b-ungoogled-chromium-80.0.3987.149-1/utils/.patches.py-wrapped", line 62, in find_and_check_patch
    if not patch_bin_path.exists():
AttributeError: 'str' object has no attribute 'exists'
```

**Environment (please complete the following information):**
 - OS/Platform and version: Linux / NixOS 19.09
 - ungoogled-chromium version: 80.0.3987.149-1

**Comment by PF4Public** [comment]
Which version of Python do you use?

**Comment by wizeman** [comment]
Sorry, but that commit does not fix this issue for me.

I'm still getting a very similar backtrace, although line numbers have changed a bit:

```
INFO: Applying patches from /nix/store/5dybgy7xv1b5vfwl31d54mh49lpfn412-ungoogled-chromium-80.0.3987.149-2/patches
Traceback (most recent call last):
  File "/nix/store/5dybgy7xv1b5vfwl31d54mh49lpfn412-ungoogled-chromium-80.0.3987.149-2/utils/.patches.py-wrapped", line 250, in <module>
    main()
  File "/nix/store/5dybgy7xv1b5vfwl31d54mh49lpfn412-ungoogled-chromium-80.0.3987.149-2/utils/.patches.py-wrapped", line 246, in main
    args.callback(args, parser.error)
  File "/nix/store/5dybgy7xv1b5vfwl31d54mh49lpfn412-ungoogled-chromium-80.0.3987.149-2/utils/.patches.py-wrapped", line 201, in _apply_callback
    patch_bin_path=args.patch_bin)
  File "/nix/store/5dybgy7xv1b5vfwl31d54mh49lpfn412-ungoogled-chromium-80.0.3987.149-2/utils/.patches.py-wrapped", line 113, in apply_patches
    patch_bin_path = find_and_check_patch(patch_bin_path=patch_bin_path)
  File "/nix/store/5dybgy7xv1b5vfwl31d54mh49lpfn412-ungoogled-chromium-80.0.3987.149-2/utils/.patches.py-wrapped", line 62, in find_and_check_patch
    if not patch_bin_path.exists():
AttributeError: 'str' object has no attribute 'exists'
```

I'm running python 3.7.5.

**Comment by wizeman** [comment]
For reference, I believe these are the arguments being used:
```
$ /nix/store/(...ungoogled...)/utils/patches.py apply --patch-bin /nix/store/(...patch...)/bin/patch . /nix/store/(...ungoogled...)/patches
